name: Install Module And Cache

description: Setup Environment Variables for Django Project

runs:
  using: composite
  steps:
    - name: Install mise
      uses: jdx/mise-action@156251fcc627ac4e26cb0f93dd47d1d4979abf24 # v3.3.0
      with:
        version: "2025.10.2"
        install_args: "node pnpm gitleaks"

    - name: Setup pnpm cache (GitHub optimized)
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        cache: "pnpm"
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
