name: Install Module And Cache

description: Setup Environment Variables for Django Project

runs:
  using: composite
  steps:
    - name: Install mise
      uses: jdx/mise-action@156251fcc627ac4e26cb0f93dd47d1d4979abf24 # v3.3.0
      with:
        version: "2025.10.2"
        install: false
        install_args: "node pnpm"

    # - name: Install tools
    #   shell: bash
    #   run: mise i node pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
      env:
        HUSKY: 0
