# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: check lint

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'npm'
    - name: package install
      run: npm ci
    - name: run lint
      run: |
        npm run lint
      env:
        NODE_ENV: production
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply Prettier Change
        ref: ${{ github.head_ref }}
