name: unit test

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: 高速化したくなったらactions/cacheでnode_modulesをcache
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: package install
        run: npm ci
      - name: run lint
        run: |
          npm run lint
        env:
          NODE_ENV: production
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Prettier Change
          ref: ${{ github.head_ref }}
